### ISSUE TITLE
Additional info in report

### ISSUE THREAD

**Issue by banesullivan** [banesullivan/scooby#10]
What else should be in the report?

Also, checkout `mne-python`'s `mne.sys_info` method from https://github.com/pyvista/pyvista/issues/186#issuecomment-485546991

> additional info (as given by import mne; mne.sys_info()):
>
> ```
> Platform:      Windows-10-10.0.17763-SP0
> Python:        3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
> Executable:    C:\Users\mmagn\Continuum\anaconda3\python.exe
> CPU:           Intel64 Family 6 Model 158 Stepping 10, GenuineIntel: 12 cores
> Memory:        15.9 GB
>
> numpy:         1.16.2 {blas=mkl_rt, lapack=mkl_rt}
> matplotlib:    3.0.2 {backend=module://ipykernel.pylab.backend_inline}
> mayavi:        4.6.2 {qt_api=pyqt5, PyQt5=5.9.2}
> ```

**Comment by prisae** [comment]
I like the blas/lapack-info from numpy. In particular, if mkl/numexpr are not installed and therefore `MKL_INFO=False`. Maybe we could put that info into `MKL_INFO` if `mkl=False` and `numexpr=False`?

**Comment by banesullivan** [comment]
Closing since blas/lapack-info are their own issue in #54
