### ISSUE TITLE
`codecov` PyPI package removed as deprecated

### ISSUE THREAD

**Issue by adamgranthendry** [banesullivan/scooby#110]
## Issue

`codecov` was [removed from PyPI as deprecated](https://about.codecov.io/blog/message-regarding-the-pypi-package/), but `scooby`'s `requirements_test.txt` still includes `codecov`. Thus, `pip` installing the test dependencies fails.

Also, for those using `poetry`, installing with `poetry add` fails since [`poetry` requires all dependencies to be compatible with each other and resolvable during install regardless of whether they are required for install](https://python-poetry.org/docs/managing-dependencies/). Hence, using `poetry add scooby` results in the error `Package codecov (2.1.12) not found.`.

## Recommendation

Per the [deprecation guide](https://docs.codecov.com/docs/deprecated-uploader-migration-guide):

  1. Remove codecov from `requirements_test.txt`
  2. Replace any calls to Codecov with the new [Codecov Uploader](https://docs.codecov.com/docs/codecov-uploader)
  3. If you are using [coveragepy](https://coverage.readthedocs.io/en/6.0/) to collect code coverage, you will need to add
       ```
       coverage xml
       ```
       before calling the new uploader.

**NOTE:** Version `2.1.13`, but **not** `2.1.12`, was reinstated to PyPI [see post-mortem message 1](https://about.codecov.io/blog/message-regarding-the-pypi-package/) and [2](https://about.codecov.io/blog/post-mortem-of-codecov-pypi-package-removal/), but it appears all language-specific uploaders will eventually be deprecated (they haven't released the schedule yet, AFAIK). Using `2.1.13` might be a temporary workaround, but it may be wiser to focus the energy on following the deprecation guide steps instead.

**Comment by adamgranthendry** [comment]
@banesullivan I noticed coverage status's are off in the `coverage.yml`. If you just need a diff to appear in PRs, [Hynek's article](https://hynek.me/articles/ditch-codecov-python/) might interest you. It shows how to output an HTML table with `coverage` to `$GITHUB_STEP_SUMMARY`.

**Comment by banesullivan** [comment]
Fixed in #112
