### ISSUE TITLE
Show info about Scooby in the report

### ISSUE THREAD

**Issue by banesullivan** [banesullivan/scooby#14]
We should also add a header line to show info about the version of Scooby being used to make the report. Perhaps something light-hearted and simple like:

```
>>> scooby.investigate()
------------------------------------------------------
  Looks like we've got another mystery on our hands!
  Scooby 0.2.1 reporting for duty!
  Date: Sat Jun 29 14:32:01 2019 MDT
...
```

**Comment by prisae** [comment]
For the widest possible adaption I would opt to keep it very dry and simple. How about reporting scooby in the empty field below 'machine', right of 'RAM'?

Or just in the section of numpy etc...

**Comment by banesullivan** [comment]
I think it makes the most sense to put it in the Python package section if not in a preamble. I just changed #15 to the following by putting Scooby's version in the report's internal dictionary of package versions (and since it's Python 3, the order is preserved so `scooby` would always appear first)

```py

------------------------------------------------------
  Date: Sat Jun 29 14:45:40 2019 MDT
  Platform: Darwin-18.5.0-x86_64-i386-64bit

             12 : CPU(s)
         x86_64 : Machine
          64bit : Architecture
        32.0 GB : RAM

  3.7.3 | packaged by conda-forge | (default, Mar 27
  2019, 15:43:19)  [Clang 4.0.1
  (tags/RELEASE_401/final)]

         Python : Environment

          0.2.1 : scooby
         1.16.3 : numpy
          1.3.0 : scipy
          7.5.0 : IPython
          3.1.0 : matplotlib

  Intel(R) Math Kernel Library Version 2018.0.3
  Product Build 20180406 for Intel(R) 64
  architecture applications
------------------------------------------------------
```
