### ISSUE TITLE
Should packages be alphabetical?

### ISSUE THREAD

**Issue by banesullivan** [banesullivan/scooby#16]
As my https://github.com/banesullivan/scooby/issues/14#issuecomment-506986101 outlines, packages are shown by order of insertion... should they be sorted alphabetically?

But what about the core packages... would we want those first?

**Comment by banesullivan** [comment]
I imagine some projects might want to report on ~20 packages and sorting through a non-alphabetized list of those wouldn't be fun

**Comment by prisae** [comment]
IMHO: Packages should be listed in the order the user provided them. Core packages are listed in the order we think it is best. Of course, this order can be overwritten by the user.

I would first list user provided packages, then core packages. Order: Numpy, scipy, matplotlib, IPython, and scooby last.

What do you think?

**Comment by prisae** [comment]
Some projects might indeed have a huge list. But they might think about importance etc of the different packages. By sorting them we would destroy that. They, of course, could provide a sorted list. But we should leave it up to the user.

**Comment by banesullivan** [comment]
I like that.

What if we had NumPy, SciPy, Matplotlib, IPython, and `scooby` listed the defaults for the`optional` argument to investigate. That way a user could easily type the following for a package they want to include in the default report:

```py
>>> import scooby
>>> scooby.investigate('pyvista') 
------------------------------------------------------
  Date: Sat Jun 29 17:55:48 2019 MDT
  Platform: Darwin-18.5.0-x86_64-i386-64bit

             12 : CPU(s)
         x86_64 : Machine
          64bit : Architecture
        32.0 GB : RAM

  3.7.3 | packaged by conda-forge | (default, Mar 27
  2019, 15:43:19)  [Clang 4.0.1
  (tags/RELEASE_401/final)]

         Python : Environment

         0.20.4 : pyvista
         1.16.3 : numpy
          1.3.0 : scipy
          7.5.0 : IPython
          3.1.0 : matplotlib

  Intel(R) Math Kernel Library Version 2018.0.3
  Product Build 20180406 for Intel(R) 64
  architecture applications
------------------------------------------------------
```

and that way it would show the package(s) listed by the user as the `core` option and the packages that we (developers of `scooby`) think are import if they are available but not raise an alarm if those packages aren't available.

Then if you are adding pyvista as a dependency to your project to report on the stuff you care about, you could implement a function like the following which I have in https://github.com/pyvista/pyvista/pull/272

```py
def generate_report(additional=None, ncol=3, text_width=54):
    """Generate an environment report using :module:`scooby`

    Parameters
    ----------
    additional : list(ModuleType), list(str)
        List of packages or package names to add to output information.

    ncol : int, optional
        Number of package-columns in html table; only has effect if
        ``mode='HTML'`` or ``mode='html'``. Defaults to 3.

    text_width : int, optional
        The text width for non-HTML display modes

    """
    core = ['pyvista', 'vtk', 'numpy', 'imageio', 'appdirs', 'scooby']
    optional = ['matplotlib', ]
    report = scooby.investigate(core=core, optional=optional,
                                additional=additional, ncol=ncol,
                                text_width=text_width)
    return report
```

Then when a user is reporting a PyVista bug/issue, all we have to do is ask them to type `pyvista.generate_report()`. Plus they still have the option to add other packages.


Just in case some users what an alphabetized list, we could add a keyword argument to `scooby.investigate()` that would trigger a sorting of the `self._packages` dictionary.

**Comment by banesullivan** [comment]
Or should we have `scooby` always appended as the very last package to report? I'm thinking incase another package forgets to add `scooby` to their `optional` list and `scooby`'s version is relevant for some reason.

**Comment by banesullivan** [comment]
I implemented an optional way to sort everything and I like it:

<img width="930" alt="Screen Shot 2019-06-29 at 7 26 23 PM" src="https://user-images.githubusercontent.com/22067021/60391080-e3943b00-9aa3-11e9-898a-b34e04dcc111.png">
