### ISSUE TITLE
Remove `investigate`

### ISSUE THREAD

**Issue by prisae** [banesullivan/scooby#17]
I am not sure about the rationale behind `investigate`, as `scooby.investigate()` and `scooby.Report()` are identical. And there shouldn't be functions in an `__init__.py`-file. The only thing to do is move all the docstring from `investigate()` to `Report`.

I'll do a PR for that. But then there might have been some thinking/reasoning behind the decision I am not aware...?

**Comment by prisae** [comment]
It could be made backwards compatible by putting into `__init__.py`:
```
from scooby.report import Report as investigate
```

**Comment by banesullivan** [comment]
We should just remove it
