### ISSUE TITLE
GDAL Version

### ISSUE THREAD

**Issue by banesullivan** [banesullivan/scooby#21]
How do you get the version for GDAL and what else is important about GDAL?

This doesn't seem very useful:

```py
>>> import gdal
>>> gdal.VersionInfo()
'3000000'
```

or is `'3000000'` legitimately my version of GDAL and that would be insightful to developers around GDAL when bug reporting?

I feel like there are probably different compilation options that are important. Also what about `osgeo.gdal`, is that different?

**Comment by banesullivan** [comment]
Ping @leouieda: I feel like this might be relevant to GMT and/or Verde?

Do you know?/is there any particular info about GDAL that might be important?

**Comment by leouieda** [comment]
Hi @banesullivan, gdal is notorious in the geospatial stack. It would be good to have the version printed if it's found. 3000000 is not a real version number. The latest version on conda-forge is 3.0.0 (https://github.com/conda-forge/gdal-feedstock). Compiler options might have some effect but I'm not sure which. @ocefpaf is my go to when it comes to that (Filipe might also be interested in scooby).

**Comment by ocefpaf** [comment]
I use `gdal-config --version` to get the version. But if you want to do that from python you can use `gdal.VersionInfo("RELEASE_NAME")` instead.

> Filipe might also be interested in scooby

Nice project! I need to find some time to explore it more.

**Comment by banesullivan** [comment]
@ocefpaf, thanks for that tip! I'm going to include that here!

------

It's worth noting that this is currently working with GDAL install by anaconda:

```py
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:50:38)
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from scooby import Report
>>> Report(["osgeo.gdal"])

--------------------------------------------------------------------------------
  Date: Wed Nov 24 18:31:31 2021 MST

                OS : Darwin
            CPU(s) : 12
           Machine : x86_64
      Architecture : 64bit
               RAM : 32.0 GiB
       Environment : Python

  Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:50:38)
  [Clang 11.1.0 ]

        osgeo.gdal : 3.4.0
             numpy : 1.21.4
           IPython : 7.29.0
            scooby : 0.5.7
--------------------------------------------------------------------------------
>>>
```

**Comment by ocefpaf** [comment]
My only problem with that report is that the method should be named:

```python
from scooby import doo
doo()
```

;-p

**Comment by leouieda** [comment]
```python
from scooby import doo as doobiedoo
```

**Comment by banesullivan** [comment]
I mean... now I _have_ to put that in the README
