### ISSUE TITLE
VERSION_ATTRIBUTES and VERSION_METHODS

### ISSUE THREAD

**Issue by prisae** [banesullivan/scooby#23]
We should provide a possibility (input parameters or set functions) to add VERSION_ATTRIBUTES and VERSION_METHODS.

**Comment by prisae** [comment]
Well, it's possible, you just have to edit the dict. I will add it to the README.

```
scooby.report.VERSION_ATTRIBUTES['module_with_strange_version_location'] = 'Awesom_version_location'
```

**Comment by prisae** [comment]
Added it to the README

**Comment by banesullivan** [comment]
We should maybe make it a bit easier and also show in the docs how to add functions that get versions like what we have for PyQt5

**Comment by prisae** [comment]
Yes, that would be great! But I thought I'd wait with that. Maybe we come along better ideas, or other (ones it is getting used) will bring some ideas. This is also why I think the two-file split makes sense, `knowledge` and `report`. I do not expect `report` to change a lot` whereas `knowledge` might as we learn along the way...
