### ISSUE TITLE
org

### ISSUE THREAD

**Issue by prisae** [banesullivan/scooby#31]
How big are you thinking scooby will go? Maybe we should move it out to its own org rather sooner than later. The only thing missing for it is probably a logo. (We could make an 8bit-image of your dog-emoticon.)

I thought of https://github.com/opengeophysics first, but it is much more general than that, so it should have its own org I think. Later there might come other modules to it for similar tasks.

**Comment by banesullivan** [comment]
I wonder if we could make a custom 8bit-image of a **detective dog**? I have little experience with graphic design but it'd be fun to try this

`scooby` is already an account on GitHub, so we'd need a different name if we made a new org.

This is definitely the most general code I've worked on... I wonder if we should seek out rescue (*dog pun*) by an org that has a more general-Python focus like (and some of these might be far reaches):

- https://github.com/pypa (makes the most sense to me)
- https://github.com/python
- https://github.com/PyCQA
- https://github.com/pytest-dev

Or perhaps:

- https://github.com/softwareunderground
- https://github.com/agu-ossi

I'm not sure how any of those orgs would feel about taking on an infant project like this or if we'd want to migrate this project to people we don't know... If another more general org was interested, it would definitely bring a lot more developers on board (in theory).

**Comment by prisae** [comment]
Might be an idea. I was thinking of numpy/scipy once, but then again, it is more general than that.

pypa might be an idea or python, or also conda-forge. But then I am not sure how open these big organisations are for new things. There would be no harm in asking though.

**Comment by banesullivan** [comment]
Let's make a sweet logo then send out emails. `conda-forge` is another good one I forgot about.

Do you have experience making logos and graphics? Any good tools for this?

**Comment by prisae** [comment]
Something along this: https://www.shutterstock.com/image-vector/pixel-beagle-dog-portrait-detailed-isolated-1175291248?id=1175291248&irgwc=1&utm_medium=Affiliate&utm_campaign=Eezy%2C+LLC&utm_source=38919&utm_term=www.vecteezy.com ?

**Comment by prisae** [comment]
https://www.vecteezy.com/free-vector/pixel-dog?license-standard=true

**Comment by prisae** [comment]
> Do you have experience making logos and graphics?

Nope. The logos for empymod and emg3d are the only attempts, and not particularly good ones...

**Comment by prisae** [comment]
I use this to create favicons; it could also help to create a pixelated image I guess... http://www.xiconeditor.com/

**Comment by prisae** [comment]
On the other hand - most things we deal with do at least use NumPy, right? Not necessarily SciPy, but NumPy yes. So it could also be something to include in NumPy?

**Comment by banesullivan** [comment]
Numpy does make sense - same with other libraries at the foundation of the OS Python Stack (numpy being the foundation)

**Comment by prisae** [comment]
This could actually be a nice fit. But then it has to be more mature. They don't want to include something that is still changing a lot.

**Comment by prisae** [comment]
Let's keep it here for a while and think about it again.

**Comment by banesullivan** [comment]
Sounds good to me! Gives us time to focus on the more important things: making an awesome logo 😄

**Comment by prisae** [comment]
Yes and no. If it would be to be included in a big library like NumPy, then there would be no need for a logo...

**Comment by banesullivan** [comment]
Oh you mean actually in Numpy like `numpy.Report()`? 👀 that’d be next level

**Comment by prisae** [comment]
Yes, but even if it just would live in a big repo such as https://github.com/numpy there wouldn't actually be a need for a logo, I think.

**Comment by prisae** [comment]
> Oh you mean actually in Numpy like numpy.Report()? eyes that’d be next level

I will definitely ask in the mailing list. The answer will be most likely a No, this belongs to a separate repo. But again, asking is good, and people will hear about it because of that.
