### ISSUE TITLE
sphinx-gallery rendering

### ISSUE THREAD

**Issue by prisae** [banesullivan/scooby#45]
Would be nice to define style-settings to achieve a nicer rendering with sphinx-gallery.

# nbviewer
Nicest and closest to how it actually looks in a notebook.

![nbviewer](https://user-images.githubusercontent.com/8020943/74252167-8b860e00-4ced-11ea-9e7b-382ce6019db9.png)

# GitHub
Acceptable, readable, but not perfect.

![GitHub](https://user-images.githubusercontent.com/8020943/74252187-90e35880-4ced-11ea-8476-013c5baf12d3.png)

# Sphinx-Gallery with RTD theme
Not nice, crowded and hard to read.

![sphinx-gallery](https://user-images.githubusercontent.com/8020943/74252207-98a2fd00-4ced-11ea-8521-91a8c69adb7c.png)

**Comment by prisae** [comment]
Adding `cellpading="4"` and `fontsize: smaller` improves it already a lot. 
```
<table style="font-size: smaller; border: 3px solid #ddd;" cellpadding="4">
```
however, that was just playing around in the Firefox dev-console. No idea how to implement that nicely in a sphinx-css (or in scooby?).

That is how it looks like in Sphinx-Gallery with the changes:

![sphinx-with-changes](https://user-images.githubusercontent.com/8020943/74254665-0b61a780-4cf1-11ea-8f27-8b683b02d1f5.png)

**Comment by banesullivan** [comment]
> Adding cellpading="4" and fontsize: smaller improves it already a lot.

Should be as simple as adding here:

https://github.com/banesullivan/scooby/blob/cf35d596810791ec292e08fb11ed0973a34c0696/scooby/report.py#L293
