### ISSUE TITLE
Feature request: detect whether in script/jupyter/ipython

### ISSUE THREAD

**Issue by leouieda** [banesullivan/scooby#5]
I imagine this is something that a lot of visualization libraries would want. There are some ways of telling if the kernel is IPython but I'm not sure if there is any robust way of knowing if on a notebook. It might expand the usage of Scooby beyond capturing an environment metadata in a notebook.

**Comment by banesullivan** [comment]
We actually figured this out in PyVista with this little snippet:

```py
def run_from_ipython():
    """ returns True when run from IPython """
    try:
        py = __IPYTHON__
        return True
    except NameError:
        return False

notebook = None
if run_from_ipython():
    try:
        notebook = type(get_ipython()).__module__.startswith('ipykernel.')
    except NameError:
        pass
```

The variable `notebook` will let you know if you are in a notebook - or at least this works for PyVista so that we can default to use different viewing styles if a user is calling from normal python, IPython, or a Jupyter notebook.

I image we could clean this up and make it a bit more general/useful

**Comment by banesullivan** [comment]
And proof that it works:

<img width="630" alt="Screen Shot 2019-06-25 at 6 55 16 PM" src="https://user-images.githubusercontent.com/22067021/60143313-d06b2d80-977a-11e9-95a3-6788b3072b49.png">


<img width="751" alt="Screen Shot 2019-06-25 at 6 55 08 PM" src="https://user-images.githubusercontent.com/22067021/60143315-d234f100-977a-11e9-81b9-f53982fa976d.png">

**Comment by leouieda** [comment]
Ooh nice! Just confirmed that it works on JupyterLab as well. How would you feel about having this in Scooby as a function? I'd love to use it in PyGMT and wouldn't mind adding Scooby as a dependency.

**Comment by banesullivan** [comment]
Sounds good to me! I'll see if I can generalize this snippet later tonight then implement it

how should it be called? Suggestions?

Perhaps:

```py
import scooby
scooby.in_ipython()
scooby.in_jupyter()
```

Then you could step through the three possible scenarios with the following logic:

```py
import scooby

if scooby.in_jupyter():
    # Do Jupyter stuff
elif scooby.in_ipython():
    # Do IPython stuff
else:
    # Do normal, boring Python stuff
```

**Comment by leouieda** [comment]
That looks good to me :)

**Comment by prisae** [comment]
Just saw that now, after opening issue https://github.com/banesullivan/scooby/issues/8 . This method does not always work, and so far I do not know a method that can say absolutely that you are in a notebook. The thing is, notebooks use the kernel, but a kernel can also be used by other things... So `scooby.in_jupyter` yields `True` if you are, in fact, in a QtConsole (or other tools making use of the kernel).

**Comment by leouieda** [comment]
Ah, that was my main concern. I always forget about the console. The whole "frontend agnostic" approach of Jupyter seems good in principle but I haven't able to make it work reliably in practice. I'll take the guess of maybe being in a notebook over not having a clue. But maybe we should rename the function `is_ipykernel`?

**Comment by banesullivan** [comment]
Bummer...

Fair to rename that function to `is_ipykernel` instead

**Comment by prisae** [comment]
There might be a trick... So in jupyter, the output will be html, right. In the console, it will be text. Could we do a test `scooby.investigate` and see if the output has any html-tags?

**Comment by banesullivan** [comment]
Ah yup, I went down that path and dived into IPython's source code to figure out how they decide to use the HTML repo method... which is how I made: https://github.com/banesullivan/scooby/issues/8#issuecomment-505768933

**Comment by prisae** [comment]
Nope, I don't think so.

Here, from a core-dev:
https://github.com/bokeh/bokeh/issues/1895#issuecomment-74453564

Citing
> Technically you *can not* know if you are in the notebook!

**Comment by leouieda** [comment]
Yeah, I figured that was the case. Thanks for the references @prisae. It is still useful to know if using ipykernel out of ipython since even in the qt gui we probably don't want pop up windows but pngs
