### ISSUE TITLE
deploy source dist

### ISSUE THREAD

**Issue by banesullivan** [banesullivan/scooby#56]
see https://github.com/conda-forge/pyvista-feedstock/issues/29

@akaszynski, can you handle on this?

**Comment by akaszynski** [comment]
Made a quick patch to master and manually uploaded sdist so we don't have to tag.

**Comment by banesullivan** [comment]
Sounds good to me. If I remember correctly, the last release was only to ship a wheel. So the version on cond-forge is still the same?

**Comment by akaszynski** [comment]
Correct, last release was to just ship the wheel, but I think we should get a conda-forge request anyway as it's automatically triggered when a sdist is uploaded.
