### ISSUE TITLE
Color scheme in Jupyter Darkmode

### ISSUE THREAD

**Issue by PythonFZ** [banesullivan/scooby#62]
I am using Jupyter Lab with dark mode enabled and the output of `scooby.Report()` does not adapt to the dark colors.

![JupyterLabDarkMode](https://user-images.githubusercontent.com/46721498/115160435-654dc200-a098-11eb-9fe1-650e0b55ed1f.png)

**Comment by prisae** [comment]
Thanks for reporting. I guess we should choose colours which work for both, dark and bright.

**Comment by prisae** [comment]
Do you use pandas or xarray @PythonFZ ? How do those tables look like? We should probably mimic that if it is good, no need to invent something of our own.

**Comment by PythonFZ** [comment]
Pandas looks something like this

![image](https://user-images.githubusercontent.com/46721498/115236201-5c520480-a11b-11eb-9bfa-df9a03a5a8e3.png)

**Comment by prisae** [comment]
Neat. So we could copy their behaviour. Do you want to have a stab @PythonFZ ?

**Comment by PythonFZ** [comment]
I don't think I have the time to look at it right now. I may have a look at it in the future, if no one else closed the issue by then.

**Comment by prisae** [comment]
Same here. I also added the `good first issue` label.

**Comment by prisae** [comment]
We should really fix this. More and more themes have dark modes implemented, and it looks horrible... E.g., https://empymod.emsig.xyz/en/latest/gallery/educational/dlf_standard_lagged_splined.html

![2022-06-25-01](https://user-images.githubusercontent.com/8020943/175771314-c4fd37d1-0d1d-4869-bf1b-8f8a330290f7.png)

Any quick and easy ideas @banesullivan , @akaszynski ?
