### ISSUE TITLE
Flaky tests on Windows and Mac runners

### ISSUE THREAD

**Issue by banesullivan** [banesullivan/scooby#71]
I’m seeing some tests flakily fail when doing string comparisons on the mac and windows runners… not linux though

https://github.com/banesullivan/scooby/runs/4326663103?check_suite_focus=true#step:7:62

**Comment by prisae** [comment]
The problem is the time stamp between the two strings.
Changing
```
assert text_html == text_plain[5:]
```
to 
```
assert text_html[20:] == text_plain[25:]
```
will fix that.

**Comment by prisae** [comment]
(It is a 1 second time difference in the time stamp; the two versions are done immediately one after the other, but it can happen that these are in a different 'second'.)
