### ISSUE TITLE
File System unknown

### ISSUE THREAD

**Issue by prisae** [banesullivan/scooby#78]
I get a
```
File system : unknown
```

Related to #76

Before, this section was omitted if not found (mainly because `psutil` is not installed). With #76, it is shown even if unknown.

[*Message was edited to reflect what I found for creating #80.*]

**Comment by banesullivan** [comment]
I've also been getting this on my PC

I think it is related to #75

**Comment by prisae** [comment]
If `unknown` is all we get on any OS then we better take `File system` out until we have a proper fix, what do you think?

Maybe @PythonFZ has an idea (from #61)?

**Comment by banesullivan** [comment]
I agree - we should at least not include it if `unknown`

**Comment by prisae** [comment]
I'll quick have a stab.
